# Generated by Django 4.2.5 on 2023-09-05 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("street", models.CharField(max_length=150)),
                ("number", models.CharField(max_length=20, null=True)),
                ("district", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=5)),
                ("zip_code", models.IntegerField(max_length=8)),
            ],
        ),
    ]
