# Generated by Django 4.2.5 on 2023-09-05 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "hour",
                    models.TimeField(
                        choices=[
                            ("8:00", "H01"),
                            ("8:30", "H02"),
                            ("9:00", "H03"),
                            ("9:30", "H04"),
                            ("10:00", "H05"),
                            ("10:30", "H06"),
                            ("11:00", "H07"),
                            ("11:30", "H08"),
                            ("12:00", "H09"),
                            ("12:30", "H10"),
                            ("13:00", "H11"),
                            ("13:30", "H12"),
                            ("14:00", "H13"),
                            ("14:30", "H14"),
                            ("15:00", "H15"),
                            ("15:30", "H16"),
                            ("16:00", "H17"),
                            ("16:30", "H18"),
                            ("17:00", "H19"),
                            ("17:30", "H20"),
                            ("18:00", "H21"),
                            ("18:30", "H22"),
                            ("19:00", "H23"),
                            ("19:30", "H24"),
                        ]
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_schedules",
                        to="properties.property",
                    ),
                ),
            ],
        ),
    ]
